const host = process.env.VUE_APP_HOST || ''
const root = host

export const directions = `${root}/map/directions`
export const login = `${root}/user/login`
export const register = `${root}/user/register`

export const riding = `${root}/map/riding`
export const riding_underway = `/map/riding/underway`
export const riding_stop = `${root}/map/riding/stop`
export const upload = `${root}/file_upload`
export const article = `${root}/article/create`
export const article_info = `${root}/article/info`
export const article_list = `${root}/article/list`
export const article_agree = `${root}/article/agree`
export const article_remove = `${root}/article/delete`
export const article_update = `${root}/article/update`
export const comment = `${root}/comment/list`
export const comment_create = `${root}/comment/create`
export const comment_remove = `${root}/comment/delete`
export const user_fans = `${root}/user/fans`
export const follow = `${root}/user/follow`
export const follow_remove = `${root}/user/follow/remove`
export const user_query = `${root}/user/query`
export const user_update = `${root}/user/update`
export const user_ranking = `${root}/map/riding/list`
export const active_create = `${root}/active/create`
export const active_list = `${root}/active/list`
export const active_update = `${root}/active/update`
export const active_user_add = `${root}/active/user/add`
export const active_user_del = `${root}/active/user/del`
export const active_info = `${root}/active/info`
export const active_me_list = `${root}/active/me/list`
export const active_delete = `${root}/active/delete`
export const user_route = `${root}/map/list`
export const user_route_delete = `${root}/map/route/delete`
export const riding_byId = `${root}/map/riding_byId`
export const user_week_report = `${root}/map/riding/week`